export const WIKIPEDIA_API_BASE = 'https://en.wikipedia.org/w/api.php';
export const DEFAULT_TARGET = 'Adolf Hitler';
export const DEFAULT_TARGET_DISPLAY = 'Adolf Hitler';

// Curated list of well-known Wikipedia articles for daily puzzles.
// These are chosen to be interesting starting/ending points that are
// well-connected and recognizable to most players.
export const CURATED_ARTICLES = [
  'Albert Einstein', 'Leonardo da Vinci', 'Cleopatra', 'Napoleon',
  'William Shakespeare', 'Nikola Tesla', 'Marie Curie', 'Julius Caesar',
  'Genghis Khan', 'Isaac Newton', 'Charles Darwin', 'Galileo Galilei',
  'Alexander the Great', 'Aristotle', 'Plato', 'Socrates',
  'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Vincent van Gogh',
  'Pablo Picasso', 'Michelangelo', 'Rembrandt', 'Claude Monet',
  'Frida Kahlo', 'Salvador Dalí',
  'Queen Victoria', 'Elizabeth II', 'Abraham Lincoln', 'George Washington',
  'Thomas Jefferson', 'Benjamin Franklin', 'Theodore Roosevelt',
  'Franklin D. Roosevelt', 'John F. Kennedy', 'Martin Luther King Jr.',
  'Mahatma Gandhi', 'Nelson Mandela', 'Winston Churchill',
  'Moon', 'Sun', 'Earth', 'Mars', 'Jupiter', 'Saturn',
  'Milky Way', 'Black hole', 'DNA', 'Photosynthesis', 'Evolution',
  'Gravity', 'Speed of light', 'Quantum mechanics', 'Theory of relativity',
  'Atom', 'Electron', 'Periodic table',
  'Great Wall of China', 'Pyramids of Giza', 'Colosseum', 'Taj Mahal',
  'Eiffel Tower', 'Statue of Liberty', 'Machu Picchu', 'Stonehenge',
  'Amazon River', 'Nile', 'Pacific Ocean', 'Atlantic Ocean',
  'Mount Everest', 'Grand Canyon', 'Sahara', 'Antarctica',
  'Cat', 'Dog', 'Horse', 'Elephant', 'Lion', 'Tiger', 'Eagle',
  'Dolphin', 'Whale', 'Shark', 'Octopus', 'Butterfly', 'Bee',
  'Dinosaur', 'Tyrannosaurus', 'Mammoth',
  'Pizza', 'Chocolate', 'Coffee', 'Tea', 'Beer', 'Wine', 'Bread',
  'Rice', 'Sushi', 'Cheese',
  'Football', 'Basketball', 'Baseball', 'Tennis', 'Cricket',
  'Olympic Games', 'FIFA World Cup', 'Super Bowl',
  'Internet', 'World Wide Web', 'Artificial intelligence',
  'Computer', 'Smartphone', 'Television', 'Radio', 'Telephone',
  'Steam engine', 'Printing press', 'Electricity', 'Nuclear weapon',
  'Space Shuttle', 'International Space Station', 'Apollo 11',
  'Bible', 'Quran', 'Buddhism', 'Hinduism', 'Christianity', 'Islam',
  'Democracy', 'Communism', 'Capitalism', 'United Nations',
  'World War I', 'World War II', 'Cold War', 'French Revolution',
  'American Revolution', 'Industrial Revolution', 'Renaissance',
  'Ancient Rome', 'Ancient Greece', 'Ancient Egypt', 'Roman Empire',
  'Byzantine Empire', 'Ottoman Empire', 'British Empire', 'Mongol Empire',
  'United States', 'United Kingdom', 'France', 'Germany', 'Japan',
  'China', 'India', 'Russia', 'Brazil', 'Australia', 'Canada',
  'Mexico', 'Italy', 'Spain', 'Egypt', 'South Africa', 'Nigeria',
  'Argentina', 'Sweden', 'Norway', 'Switzerland',
  'New York City', 'London', 'Paris', 'Tokyo', 'Rome', 'Berlin',
  'Moscow', 'Beijing', 'Sydney', 'Cairo', 'Istanbul',
  'Harry Potter', 'Star Wars', 'The Lord of the Rings',
  'The Beatles', 'Michael Jackson', 'Elvis Presley', 'Bob Dylan',
  'Walt Disney', 'Charlie Chaplin', 'Alfred Hitchcock',
  'Titanic', 'Wright brothers', 'Penicillin', 'Vaccination',
  'Piano', 'Guitar', 'Violin', 'Orchestra',
  'Chess', 'Poker', 'Soccer', 'Marathon',
  'Volcano', 'Earthquake', 'Hurricane', 'Tsunami',
  'Gold', 'Diamond', 'Iron', 'Oil',
  'Mathematics', 'Philosophy', 'Psychology', 'Economics',
  'Astronomy', 'Physics', 'Chemistry', 'Biology',
  'Novel', 'Poetry', 'Theatre', 'Opera', 'Ballet',
  'Painting', 'Sculpture', 'Architecture', 'Photography',
  'Automobile', 'Airplane', 'Bicycle', 'Submarine', 'Rocket',
  'Oxygen', 'Water', 'Carbon dioxide', 'Hydrogen',
  'Rainforest', 'Coral reef', 'Glacier', 'Desert',
  'Human brain', 'Heart', 'Blood', 'Skeleton',
  'Language', 'Alphabet', 'Writing', 'Braille',
  'Calendar', 'Clock', 'Compass', 'Telescope', 'Microscope',
  'Magna Carta', 'Declaration of Independence',
  'Constitution of the United States', 'Treaty of Versailles',
  'Mona Lisa', 'The Starry Night', 'The Last Supper',
  'Hamlet', 'Romeo and Juliet', 'Odyssey', 'Iliad',
  'Robin Hood', 'King Arthur', 'Dracula', 'Frankenstein',
  'Mars rover', 'Hubble Space Telescope', 'Large Hadron Collider',
  'Panama Canal', 'Suez Canal', 'Trans-Siberian Railway',
  'Silk Road', 'Spice trade',
  'Chocolate chip cookie', 'Ice cream', 'Hamburger', 'Pasta',
  'Maple syrup', 'Honey', 'Sugar', 'Salt', 'Pepper',
  'Rose', 'Sunflower', 'Oak', 'Bamboo', 'Cactus',
  'Penguin', 'Polar bear', 'Gorilla', 'Cheetah', 'Hippopotamus',
  'Crocodile', 'Python', 'Parrot', 'Flamingo',
  'Soccer', 'Rugby', 'Golf', 'Swimming', 'Gymnastics',
  'Mount Rushmore', 'Big Ben', 'Leaning Tower of Pisa',
  'Niagara Falls', 'Victoria Falls', 'Great Barrier Reef',
  'Amazon rainforest', 'Yellowstone National Park',
  'Vatican City', 'Monaco', 'Singapore', 'Iceland', 'New Zealand',
  'Hawaii', 'Madagascar', 'Greenland', 'Bermuda Triangle',
  'Vampire', 'Zombie', 'Werewolf', 'Unicorn', 'Dragon',
  'Pirate', 'Viking', 'Samurai', 'Knight', 'Gladiator',
  'Chocolate cake', 'Pancake', 'Waffle', 'Donut',
  'Tornado', 'Lightning', 'Rainbow', 'Aurora',
  'Gravity', 'Magnetism', 'Sound', 'Light',
  'Fibonacci number', 'Pi', 'Infinity', 'Prime number',
  'Cryptography', 'Morse code', 'Binary number',
  'Robot', 'Drone', 'Virtual reality', 'Blockchain',
  'Climate change', 'Ozone layer', 'Renewable energy', 'Solar energy',
  'Recycling', 'Plastic', 'Fossil fuel',
  'Nobel Prize', 'Pulitzer Prize', 'Academy Awards',
  'Monopoly (game)', 'Rubik\'s Cube', 'LEGO', 'Barbie',
  'Coca-Cola', 'McDonald\'s', 'Nike, Inc.', 'Apple Inc.',
  'Google', 'Amazon (company)', 'Microsoft', 'Tesla, Inc.',
  'SpaceX', 'NASA', 'European Space Agency',
];
